version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/sessions:/app/sessions
    environment:
      FLASK_SECRET_KEY: your_secret_key"
      GOOGLE_API_KEY: "AIzaSyD1lYasJ5bYpVWORd7qbfwy6udIW8QI81M"
      GEMINI_API_KEY: "AIzaSyDSNhcVRmJNRbqrVQOLUmMrQmUF_Yd-QL8"
      GOOGLE_REDIRECT_URI: http://localhost:5000/callback
    networks:
      - studybuddy-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - studybuddy-net

networks:
  studybuddy-net:
